Feature/dsnd 2789 fix
companieshouse/psc-data-api pull request #138
Opened 2024-07-29 14:56 UTC by SALMANCH007

2024-07-29 15:54 UTC, YaaseenR approved these changes

2024-07-29 16:02 UTC, JAndrewCH requested changes

2024-07-29 16:02 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/pscdataapi/PscDataApiApplicationTests.java
> +//    @MockBean
remove commented out mock

2024-07-29 16:02 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/pscdataapi/api/ResourceChangedApiServiceAspectFeatureFlagDisabledITest.java
> +//    @MockBean
can remove

2024-07-29 16:02 UTC, JAndrewCH commented on src/test/java/uk/gov/companieshouse/pscdataapi/api/ResourceChangedApiServiceAspectFeatureFlagEnabledITest.java
> +//    @MockBean
can remove

2024-07-30 07:09 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-07-30 08:32 UTC, JAndrewCH approved these changes

2024-07-30 08:34 UTC, merged